//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeasuresAdvanticMiddlewareDownloader.AdvanticWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:DataControllerwsdl", ConfigurationName="AdvanticWS.DataControllerPortType")]
    public interface DataControllerPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataControllerwsdl#getData", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getData(string key, string idsenal, string ini, string fin, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataControllerwsdl#getLocations", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getLocations(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataControllerwsdl#getDevices", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getDevices(string key, string idlocalizacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataControllerwsdl#getSignals", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getSignals(string key, string iddispositivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataControllerwsdl#setControl", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string setControl(string key, string ip, string port, string id, string reg, string @switch, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataControllerwsdl#getRequest", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getRequest(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataControllerwsdl#getLastRequest", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getLastRequest(string key, string senal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataControllerPortTypeChannel : MeasuresAdvanticMiddlewareDownloader.AdvanticWS.DataControllerPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataControllerPortTypeClient : System.ServiceModel.ClientBase<MeasuresAdvanticMiddlewareDownloader.AdvanticWS.DataControllerPortType>, MeasuresAdvanticMiddlewareDownloader.AdvanticWS.DataControllerPortType {
        
        public DataControllerPortTypeClient() {
        }
        
        public DataControllerPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataControllerPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataControllerPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataControllerPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getData(string key, string idsenal, string ini, string fin, string type) {
            return base.Channel.getData(key, idsenal, ini, fin, type);
        }
        
        public string getLocations(string key) {
            return base.Channel.getLocations(key);
        }
        
        public string getDevices(string key, string idlocalizacion) {
            return base.Channel.getDevices(key, idlocalizacion);
        }
        
        public string getSignals(string key, string iddispositivo) {
            return base.Channel.getSignals(key, iddispositivo);
        }
        
        public string setControl(string key, string ip, string port, string id, string reg, string @switch, string type) {
            return base.Channel.setControl(key, ip, port, id, reg, @switch, type);
        }
        
        public string getRequest(string key) {
            return base.Channel.getRequest(key);
        }
        
        public string getLastRequest(string key, string senal) {
            return base.Channel.getLastRequest(key, senal);
        }
    }
}
